#! /bin/sh

/bin/mount -a

echo "
  _____      _            __       _______   _   
 |_   _|    (_)          [  |  _  |_   __ \ (_)  
   | |      __   _ .--.   | | / ]   | |__) |__   
   | |   _ [  | [ \`.-. |  | '' <    |  ___/[  |  
  _| |__/ | | |  | | | |  | |\`\ \  _| |_    | |  
 |________|[___][___||__][__|  \_]|_____|  [___]
"
for initscript in /etc/init.d/S[0-9][0-9]*
do
	if [ -x $initscript ] ;
	then
		echo "[RCS]: $initscript"
		$initscript
	fi
done

/link/shell/init.sh
